### ISSUE TITLE
Why choose Random over CryptoRandom?

### ISSUE THREAD

**Issue by LostSoulfly** [myloveCc/NETCore.Encrypt#12]
See [here](https://github.com/myloveCc/NETCore.Encrypt/blob/master/src/NETCore.Encrypt/EncryptProvider.cs#L32). Why choose Random over CryptoRandom when generating Key and IV? Since this is a sensitive key, would it not make more sense to use a more secure random number generator?

**Comment by LostSoulFly** [comment]
![image](https://user-images.githubusercontent.com/9120519/35475099-856720b8-0366-11e8-88e3-475b4639c1bb.png)

Here's the gist: https://gist.github.com/LostSoulFly/cea837b714d71ef6d6be131a405c2891

I replaced the original GetRandomStr with a new RNGCrypto provider that generates better random keys/IVs, and it's actually quite a bit faster by my testing, and ultimately, more secure (I believe).

**Comment by myloveCc** [comment]
Thanks for your issue,i will fix this at new version. This function just only provider a way to create AesKey.

**Comment by LostSoulFly** [comment]
I think I see a use for both versions. Original version makes an easier to
read key, my version makes a difficult to read key that is more random but
harder to re-use.

I also think adding an option to accept byte arrays would be good instead
of just using strings for encryption and deception!

**Comment by myloveCc** [comment]
Thanks for your proposal. That's a good idea.  Do you want to add a pull request for this feature.

**Comment by LostSoulFly** [comment]
Done. Feel free to change them to match your personal style. I just copied the existing AESEncrypt/Decrypt and changed them slightly to allow for Byte arrays.
