### ISSUE TITLE
Decrypt Filestream does not working

### ISSUE THREAD

**Issue by unfug** [myloveCc/NETCore.Encrypt#15]
Hello,

i tried to use netcore.encrypt to encrypt and decrypt a stream.
The process is: Load a filestream , then encrypt bytes , write to another file.
Next step is: Load the file, then decrypt bytes, do something with it.
Encrypt seems to be ok cause i can load the encrypted file here http://aes.online-domain-tools.com/ and decrypt. Is working.

But when i load the encrypted file into stream and then:

`        byte[] buffer = new byte[1024];
            while (stream.Read(buffer, 0, buffer.Length) > 0)
            {
                var decryptedbytes = NETCore.Encrypt.EncryptProvider.AESDecrypt(buffer, key, iv);
                //DECRYPTDBYTES IS NULL!!
            }
`
The Problem is that the decryptedbytes is null

Can you help me?

**Comment by myloveCc** [comment]
The file's buffer length is greater than 1024?

**Comment by unfug** [comment]
Hi, 
Ty for your help. In your test you read the complete file before you en/decrypt. 
The Problem is i cant read the complete file at once. Too big or maybe a temporary file for a external stream.
So what i did is:
**Encrypt:**
2 Filestreams. 1 one for read a file , 1 for Write a encrypted file.

```cs
 using (var stream = new FileStream(@"c:\temp\bigfile.txt", FileMode.Open))
 using (var encryptedStream = new FileStream(@"c:\temp\bigfile.enc", FileMode.Create))
  {
            byte[] buffer = new byte[1024];
            while (stream.Read(buffer, 0, buffer.Length)>0)
            {
                var encryptedbuffer =  NETCore.Encrypt.EncryptProvider.AESEncrypt(buffer, key, iv);
                await encryptedStream.WriteAsync(encryptedbuffer, 0, encryptedbuffer.Length);
            }
  }
```
What happened is that a new encrypted file is generated.

But now i cant decrypt like this
```cs
 using (var stream = new FileStream(@"c:\temp\bigfile.enc", FileMode.Open))
            using (var decryptedStream= new FileStream(@"c:\temp\bigfiledecryted.txt", FileMode.Create))
            {
             byte[] buffer = new byte[1024];
            while (stream.Read(buffer, 0, buffer.Length) > 0)
            {
                var decryptedbytes = NETCore.Encrypt.EncryptProvider.AESDecrypt(buffer, key, iv);
                await decryptedStream.WriteAsync(decryptedbytes, 0, decryptedbytes.Length);
            }
            }
```
the problem is that decryptedbytes is always null.

**Comment by myloveCc** [comment]
@unfug  You must set decrypt buffer's length to 1040 . Because 1024 bytes encrypted length is 1040.
``` Csharp
using (var stream = new FileStream(encryptedFilePath, FileMode.Open))
            using (var decryptedStream = new FileStream(decryptedFilePath, FileMode.Create))
            {
                var readBytes = 0;
                byte[] buffer = new byte[1040];    //Buffer length is 1040
                while ((readBytes = stream.Read(buffer, 0, buffer.Length)) > 0)
                {
                    var decryptedbytes = EncryptProvider.AESDecrypt(buffer, aesKey.Key, aesKey.IV);
                    decryptedStream.WriteAsync(decryptedbytes, 0, decryptedbytes.Length);
                }
            }
```

**Comment by unfug** [comment]
Ty. 
Its working!. So AES adds 16 bytes always on top? Interesting. 
Thank you verymuch.

**Comment by gyanex** [comment]
@myloveCc  after decryption my video file is not playable
