### ISSUE TITLE
Issue when using AESDecrypt

### ISSUE THREAD

**Issue by camerontbelt** [myloveCc/NETCore.Encrypt#23]
System.FormatException: 'Invalid length for a Base-64 char array or string.'
This is the exception. 
I am able to successfully encrypt, but when I try to decrypt it throws an exception.

**Comment by xcfr3sh** [comment]
Hi, how do you fixed it? I have the same issue.

**Comment by camerontbelt** [comment]
@xcfr3sh I have no idea

**Comment by xcfr3sh** [comment]
Oh okay, What do you've changed in your Code? Or do you have a different solution?
