### ISSUE TITLE
Bug & missing feature

### ISSUE THREAD

**Issue by MichaelYuAlreadyExists** [myloveCc/NETCore.Encrypt#25]
well, first of all, there are 2 important methods on RSA you missed.Those are Sign() and Verify().

Then, there's an important BUG about ".net Standard".
try these steps:
1.create RSA key pair and save them.
2.Create a ".net core" project and a ".net framework" (console or winform)project 
3.run your RSAEncrypt() and RSADecrypt() with the same key pair

now you may get your BUG!

**Comment by myloveCc** [comment]
First ，thanks for your suggestion, now Sign() and Verify() added.  I test step by step ,but i can't see any bug .
