### ISSUE TITLE
NETCore.Encrypt.OutofMaxlengthException trying to encrypt 123 

### ISSUE THREAD

**Issue by Denis-Evseev** [myloveCc/NETCore.Encrypt#27]
Do you know why 
`
var encrypted = EncryptProvider.RSAEncrypt(publicKey, "123");`

Retrieves: 
{"Exception of type 'NETCore.Encrypt.OutofMaxlengthException' was thrown."}

publicKey: 
```
        private const string publicKey =
        @"{""Modulus"": ""m9c88+sazyrDZv7Amrek2MCkkx0ZkHfWXCCPZuZwT8gKEH4m/VDKj6hTVNr0GbZy8ZKtiq9NAxoS5Vr+xdsE9mVJu7XmU/s+D1GnF3cubckivKzCvs63sQQ9JpGmrOkIlfGbmGUprO0HEt3FA2fua/nGh67ApyLPykYXjMQI5QE="",
""Exponent"": ""AQAB""}";
```
`

**Comment by catcherwong** [comment]
You can try to specify the `RSAEncryptionPadding`, the default value is `RSAEncryptionPadding.OaepSHA512`.

```cs
var encrypted = EncryptProvider.RSAEncrypt(key, srcString, RSAEncryptionPadding.Pkcs1);
```

**Comment by Denis-Evseev** [comment]
Can I use nopadding - Is it safe? 

Do you if it is possible to decrypt/encrypt data using PEM private/public keys?
