### ISSUE TITLE
No Support for .NetFramework Version 4.5

### ISSUE THREAD

**Issue by Romikanoni** [myloveCc/NETCore.Encrypt#31]
The package "NETCore.Encrypt 2.0.8" could not be installed. You are trying to install this package into a project that refers to ".NETFramework,Version=v4.5", but the package does not contain assembly references or content files that are compatible with this framework. Contact the package creator for more information.

**Comment by myloveCc** [comment]
.net standard 2.0 don't support .Net Framework 4.5. You can find all version here.[.NET Standard Versions](https://github.com/dotnet/standard/blob/master/docs/versions.md)
