### ISSUE TITLE
Rsa加密、解密提供了默认的编码格式（hex），可以再提供一个可选的编码格式；或者直接接受、返回byte[]；更灵活些。

### ISSUE THREAD

**Issue by FrankYao2018** [myloveCc/NETCore.Encrypt#32]
类似如下的扩展方法：
 public static string RSADecrypt(string privateKey, byte[] targetArray, RSAEncryptionPadding padding, bool isPemKey = false)
        {
            Check.Argument.IsNotEmpty(privateKey, nameof(privateKey));
            Check.Argument.IsNotNull(targetArray, nameof(targetArray));
            Check.Argument.IsNotNull(padding, nameof(padding));

            RSA rsa;
            if (isPemKey)
            {
                rsa = RsaProvider.FromPem(privateKey);
            }
            else
            {
                rsa = RSA.Create();
                rsa.FromJsonString(privateKey);
            }

            using (rsa)
            {
                byte[] decryptBytes = rsa.Decrypt(targetArray, padding);
                return Encoding.UTF8.GetString(decryptBytes);
            }
        }

**Comment by myloveCc** [comment]
这个当时的确欠考虑，应该返回格式多样化。
