### ISSUE TITLE
How to RSADecrypt in PHP?

### ISSUE THREAD

**Issue by dev-ptdi** [myloveCc/NETCore.Encrypt#33]
I have public and private key in my Net Core Web API, we create an encryption string (RSAWithPem) in our Net Core Web API and put the encrypted string into a query string of an url, the query string would be read by our PHP app and decrypt it (I have copied the private key into our PHP app for decryption), how to accomplish this?

need advice

Thanks

**Comment by myloveCc** [comment]
you  need  encrypt with different key every time?

**Comment by dev-ptdi** [comment]
Yes, that’s why we use private and public key




We are happy to help,

Winanjaya
+62 817 145779
————————————————
Sent from my iPhone. 
My apologize for the typos & brevity. 
————————————————

**Comment by myloveCc** [comment]
The request url is different every time? So, how to get the request url?

**Comment by dev-ptdi** [comment]
We have 2 web apps (php & net core web api)

We store a private key into our php server and we need to decrypt query string sent by our net core api. 



We are happy to help,

Winanjaya
+62 817 145779
————————————————
Sent from my iPhone. 
My apologize for the typos & brevity. 
————————————————

**Comment by dev-ptdi** [comment]
We have 2 web apps (php & net core web api)

We store a private key into our php server and we need to decrypt query string sent by our net core api (ie. Account Activation Email)



We are happy to help,

Winanjaya
+62 817 145779
————————————————
Sent from my iPhone. 
My apologize for the typos & brevity. 
————————————————

**Comment by myloveCc** [comment]
Are you use redis or database?When you create key at web api app, you need save key info and get key id, then send key id in the url. At php server get key info with id. I hope can help you!
