### ISSUE TITLE
x509 certificate and RSA.

### ISSUE THREAD

**Issue by mochajoe2021** [myloveCc/NETCore.Encrypt#42]
Very useful C# code, thank you. Sometimes we need the public key and private key in the x509 certificate to complete RSA encryption and decryption. If you can add this function, it will be more perfect.

**Comment by myloveCc** [comment]
> Very useful C# code, thank you. Sometimes we need the public key and private key in the x509 certificate to complete RSA encryption and decryption. If you can add this function, it will be more perfect.


Thank you, your suggestion is very good, I will add this feature later. I am busy at work, you can try the following methods yourself.

```
private static RSACryptoServiceProvider GetPrivateKey(string priKeyFile, string keyPwd) 
{ 
    var pc = new X509Certificate2(priKeyFile, keyPwd, X509KeyStorageFlags.MachineKeySet); 
    return (RSACryptoServiceProvider) pc.PrivateKey; 
} 
 
private static RSACryptoServiceProvider GetPublicKey(string pubKeyFile) 
{ 
    var pc = new X509Certificate2(pubKeyFile); 
    return (RSACryptoServiceProvider) pc.PublicKey.Key; 
}
```

**Comment by mochajoe2021** [comment]
nice!
