### ISSUE TITLE
Problems with AES 

### ISSUE THREAD

**Issue by Reivaj810** [myloveCc/NETCore.Encrypt#49]
Hi, I clone the project and update the target framework to Net 6.0  and one test is failing 
"AES decrypt success test"  when I change the scrString to a  "test AES encrypt!" all is working, but the encrypted and decrypted are not the same.

This is just a report :) 
have a good day

**Comment by myloveCc** [comment]
Thank you, I'll test it.

**Comment by rotem925** [comment]
Have the same issue in 6.0
