### ISSUE TITLE
EncryptProvider.RSAFromPublicPkcs 方法报错

### ISSUE THREAD

**Issue by rongguohao** [myloveCc/NETCore.Encrypt#57]
AsnContentException: The provided data is tagged with 'Universal' class value '16', but it should have been 'Universal' class value '2'.
公钥和私钥 是 利用 支付宝开发平台开发助手 生成的    如下
![image](https://user-images.githubusercontent.com/24221257/198943413-b00c8fdb-e1df-4ab9-978b-d24385d324cb.png)

公钥：MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyt4/XSnK6rp+FuRfawSsSqZn9kpa2c4c12wEHBa5ygdmLGlkFFOv0XGvvnBhhdyZBa+rrrdWkva+Dl9Zk42DpkDNRpkDpAEvdax0ViqZ4Rq4fK4Gs3uG4fBYIUoV2m55OqqqUzK+hlqBPTyh5jY5rHLZyJYWuWGhlFiM39YALVMvt5DqjaQBW0McrvKkID+y57VDOGS+MolM5yLgu/g0F9ph91zI/47K+421fB3mXd+ecMj82xQiR0MGrP9aZ0MbhAFFzHQrXm709+5zdgioGlXkplyZkjRT6uU55K7qtykhxBuxpbpw5AYPdjLdMr2X3JjiK8J7zyLI/HimGApO2QIDAQAB
私钥：MIIEpAIBAAKCAQEAyt4/XSnK6rp+FuRfawSsSqZn9kpa2c4c12wEHBa5ygdmLGlkFFOv0XGvvnBhhdyZBa+rrrdWkva+Dl9Zk42DpkDNRpkDpAEvdax0ViqZ4Rq4fK4Gs3uG4fBYIUoV2m55OqqqUzK+hlqBPTyh5jY5rHLZyJYWuWGhlFiM39YALVMvt5DqjaQBW0McrvKkID+y57VDOGS+MolM5yLgu/g0F9ph91zI/47K+421fB3mXd+ecMj82xQiR0MGrP9aZ0MbhAFFzHQrXm709+5zdgioGlXkplyZkjRT6uU55K7qtykhxBuxpbpw5AYPdjLdMr2X3JjiK8J7zyLI/HimGApO2QIDAQABAoIBACObdMW2Yy5mA2GjPfg7vr3vjUnWbTHTko5hICuJ9Zw3RkC/Utiag76gVLd5ZDSprpYn6ltlRKXQ9zTwmXljmlrg/ubITrJHnvvphBXnrlCrbvw7U2PHZ7pahC17onBPeanJcNHfkz9jvVFxRf1xQRg6pG0not9w+npePIPBPRC3PAMrpu3cXC7oqJb4tWGXRX7Gz3ckbkRSvvFQfXr5g/pqtchp7RdFAxroqhGeqn7lsIuXdg21L6IwrUmi4MkW68aUnC53IO3jPncqau10nw2MDdUmLJKdkcXXObIIY5fLQ2kZxuM2QcRf0Xv82OWmx/yUzXbGG3TEgA2HT/RbczECgYEA8ZC9bFUrppe5nxV5PKoXF8LHm5KGYQS+Lci2ZaOoeJMGecSTuDczE+2dWEpRrwG5mrKGGpOnUpqG0l0Ch6wo9QcyPZgaj2Yg5VAcGyaTBddgG1L2PK3wi8b8+IE1zOL5TxoiqSCd5o10LnNTGrqOXy6193XHHPpLc+540lX+7E0CgYEA1v2M64arAY89vtwOA/88O6tAy15Mc19mUoyIPMruQaEe8lgL/1/1HGIt8b2h1wy9AWC+zti5GA/llo/EVJcCzsqalQhpYRrc+a5Bh3jAsFhjrGl0WGDph2QiqbygASNUOkaCv3TzevIkV7lbs16Td10a7oxUeX7qUd8fPZaSQr0CgYEAqev6kv3GWsVXmQPt6DJtVBV7e3+ybwR7EpGhXBWnKEmjwHv6vRZ3I4l9qOF+W/CGsr7pfkBm7sAsHkW2xeDgXpvVR2Z7KGvar/OOEbssqGs7+3x8IWrpTimHQPcC9UCjxnTH9NgwukC+fP46cw7PnzyoW43JpiSads5ExxAe5fECgYEAuxjJLKdz5tWLvK+xGtViy+LLbrDQA4/AcpKOdal9E2xujCUHu+T8YQkoRrrrP0V8rthM9aIx4rji6taO27bX4LL9ODmry7AfIsL9kDIMLuudQow7jjY4xXTlnaXj8VmXkWePnaLfyd00t4s+PKlP2I8UQwmo8lr6/OkaPPTusFkCgYAqGXLKncmQsQLVyqNZi/qfdM8cvX8IrpkjyUs3opt+jLVn1JGfTtvWQXisM4KSTpiP/Y7PtDDk3cNm+DlhEz3c3JwjOGuzG0fG8BN5Xak1CR3fp0kuWeoR03EI8WAXR/GYH55TzfVQsbweRXhysr8HhZxezYloiyZkbQeDzt/P4g==

开发平台：.net 6

**Comment by rongguohao** [comment]
可以使用 ImportSubjectPublicKeyInfo方法解决问题 [https://github.com/dotnet/runtime/issues/31091](url)

**Comment by myloveCc** [comment]
好的，我夜里抽时间看下。

**Comment by quan0zhou** [comment]
- ImportRSAPublicKey从PKCS#1（[https://tools.ietf.org/html/rfc3447#appendix-A.1.1](https://tools.ietf.org/html/rfc3447#appendix-A.1.1)）导入RSAPublicKey格式（以 "BEGIN RSA PUBLIC KEY "开头的PEM密钥格式）

- ExportSubjectPublicKeyInfo以X.509 SubjectPublicKeyInfo格式导出RSA密钥（PEM密钥格式，以 "BEGIN PUBLIC KEY "开头）

**Comment by myloveCc** [comment]
@rongguohao  我这边把`rsa.ImportSubjectPublicKeyInfo(Convert.FromBase64String(publicKey), out _)`方法加入进去。 用你给的密钥，单元测试已经通过，你可以试一下。

**Comment by myloveCc** [comment]
@quan0zhou 感谢，后期这里还可以根据这个来优化。

**Comment by rongguohao** [comment]
> @rongguohao 我这边把`rsa.ImportSubjectPublicKeyInfo(Convert.FromBase64String(publicKey), out _)`方法加入进去。 用你给的密钥，单元测试已经通过，你可以试一下。
