### ISSUE TITLE
Encrypt/Decrypt Problem with RSA 

### ISSUE THREAD

**Issue by catcherwong** [myloveCc/NETCore.Encrypt#7]
When calling **RSAEncrypt** and **RSADecrypt** method in Linux/OS X , those two methods can not run well !

The main reason is that both Linux and OS X don't support **RSAEncryptionPadding.OaepSHA512** !!

And **RSAEncryptionPadding.OaepSHA512** is not optional in the source code ! 

Following [EncryptProvider.cs#L364](https://github.com/myloveCc/NETCore.Encrypt/blob/master/src/NETCore.Encrypt/EncryptProvider.cs#L364) and [EncryptProvider.cs#L383](https://github.com/myloveCc/NETCore.Encrypt/blob/master/src/NETCore.Encrypt/EncryptProvider.cs#L383)

This is also the reason why  the Unit Tests of RSA can not pass in my Mac book. 

When I change RSAEncryptionPadding from OaepSHA512 to Pkcs1 , it runs well !

When calling **RSA.Create()**  , it will create an instance of [**RSAOpenSsl**](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Security/Cryptography/RSAOpenSsl.cs)  in Linux , [**RSASecurityTransforms**](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Security/Cryptography/RSASecurityTransforms.cs)  in OS X and [**RSACng**](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Security/Cryptography/RSACng.cs) in Windows.

Is there any other considerations to use **RSAEncryptionPadding.OaepSHA512** ?

**Comment by myloveCc** [comment]
Thanks for you pull request. I just test on windows.
